### ISSUE TITLE
Add a fried question 

### ISSUE THREAD

**Issue by freedomtrain** [peermusic/desktop#57]
When I go here http://localhost:8000/#/manage-friends/authenticated
I see a manage friends pages

When I send a friend an invite and they add me as their friend...at that point are we friends or is there another step ?
What does it mean when a friend is pending ?

Thanks !!!

**Comment by perguth** [comment]
Pending means that you instance is waiting to see the invited friend online on the certain signalhub you used to generate the invite.

So that means both computers need to be able to reach the signalhubs URL **_and**_ they need to be online together at least initially. The then use the signalhub to create a p2p connection.

Every time when the browser goes offline/online peermusic will try to contact that signalhub to find the friend again.
